// src/features/comment/score/Score.tsx
import { useState } from "react";
import styles from './Score.module.scss';
import { useAppDispatch } from "app/hooks";
import { downvoteComment, sortComments, upvoteComment } from "../commentSlice";

type ScoreParams = {
    commentId:number
    score:number
}

export function Score(params:ScoreParams) {
    const dispatch = useAppDispatch()
    const handleSort = ()=>dispatch(sortComments())
    const upvoteScore = ()=>dispatch(upvoteComment(params.commentId))
        .then(handleSort);
    const downvoteScore = ()=>dispatch(downvoteComment(params.commentId))
        .then(handleSort);

    
    
    return (
        <div className={styles.score}>
            <button className='borderless' onClick={upvoteScore}>+</button>
                {params.score}
            <button className='borderless' onClick={downvoteScore}>-</button>
        </div>
    )
}

// angular/src/app/comment/score/score.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-score',
  templateUrl: './score.component.html',
  styleUrls: ['./score.component.scss']
})
export class ScoreComponent {

  @Input({required:true})
  score:number = 0;

  upvoteScore() {
    this.score += 1;
    //.then(handleSort)
  }
  downvoteScore() {
    this.score -= 1;
    //.then(handleSort)
  }
  
  // handleSort = ()=>dispatch(sortComments())

}

<div class="score">
    <button class='borderless' (click)=upvoteScore()>+</button>
        {{score}}
    <button class='borderless' (click)=downvoteScore()>-</button>
</div>
