// angular/src/app/comment/addcomment/addcomment.component.ts
import { Component, OnInit, Input, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { FormControl } from '@angular/forms';
import { UserService } from 'src/app/user/user.service';
import { CommentService } from '../comment.service';
import { UserComment } from '../user-comment.model';
import { User } from 'src/app/user/user.model';

enum ADD_COMPONENT_STYLECLASS {
  wrapper=  "addCommentWrapper",
  replying = "replying",
}

@Component({
  selector: 'app-addcomment',
  templateUrl: './addcomment.component.html',
  styleUrls: ['./addcomment.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AddcommentComponent implements OnInit {
  @Input()
  replyTo?:string;

  userImage:string = '';
  currentUser:User = User.EMPTY;

  activeFieldClass:'active' | '' = '';
  commentField:FormControl<string> = new FormControl('', {nonNullable: true});

  private _componentClass:ADD_COMPONENT_STYLECLASS[] = [ADD_COMPONENT_STYLECLASS.wrapper];
  get componentClass (){
    return this._componentClass.join(' ');
  }

  constructor(
    private cd: ChangeDetectorRef,
    private userService:UserService,
    private commentService:CommentService,
     ){ }

  ngOnInit(){
    if(this.replyTo!== undefined){
      this._componentClass.push(ADD_COMPONENT_STYLECLASS.replying);
      this.cd.markForCheck(); 
    }

    this.userService.fetchCurrentUser()
      .then(user=>{
        this.currentUser = user;
        this.userImage = user.image.png;
        this.cd.detectChanges();
      })
  }

  setIsFieldActive(isActive:boolean){
    this.activeFieldClass = isActive? 'active':'';
  }

  submitComment(){
    const creationDate = new Date();
    this.commentService.addComment(new UserComment({
      user: this.currentUser,
      content: this.commentField.value,
      id: creationDate.getTime(),
      createdAt: creationDate.toString(),
    }))
    .then(()=>this.commentField.reset());
  }

}

<div class="{{componentClass}}">
    <div class="addComment">
        <img src="{{userImage}}" alt="avatar of {{currentUser.username}}"/>
        <fieldset class="{{activeFieldClass}}" >
            <legend>Add a comment</legend>
            <textarea
                (focus)=setIsFieldActive(true)
                (blur)=setIsFieldActive(false)
                [formControl]="commentField"
                rows="3" placeholder='Add a comment'>
            </textarea>
        </fieldset>
        

        <button (click)=submitComment()>SEND</button>
    </div>
</div>

// src/features/comment/addComment/AddComment.tsx
import { useAppDispatch, useAppSelector } from 'app/hooks';
import { selectUser } from 'features/user/userSlice';
import styles from './AddComment.module.scss';
import { ReplyInfo, addComment } from '../commentSlice';
import { UserComment } from 'models/userComment';
import { useState } from 'react';

type AddCommentParams = {replyTo?:ReplyInfo, onSend?:()=>void}
const DEFAULT_COMMENT = '';
export function AddComment({replyTo, onSend}:AddCommentParams) {
    const [comment, setComment] = useState(DEFAULT_COMMENT);

    const dispatch = useAppDispatch();
    const {currentUser} = useAppSelector(selectUser);
    const userImage = currentUser.image.png

    function submitComment(){
        const newComment = new UserComment({
            id: new Date().getTime(),
            content: comment,
            user: currentUser
        });
        dispatch(addComment({
            comment: newComment,
            replyTo
        }))
        .then(()=>{
            if(onSend !== undefined) onSend();
        });
        return setComment(DEFAULT_COMMENT);
    }

    
    const componentClass = [styles.addCommentWrapper]
    if(replyTo!== undefined){
        componentClass.push(styles.replying);
    }


    return (
        <div className={componentClass.join(' ')}>
            <div className={styles.addComment}>
                <img src={userImage} alt={"avatar of "+currentUser.username}/>
                <fieldset >
                    <legend>Add a comment</legend>
                    <textarea rows={3} onChange={e=>setComment(e.target.value)} placeholder='Add a comment' value={comment}/>
                </fieldset>
                

                <button onClick={()=>submitComment()}>SEND</button>
            </div>
        </div>
    )
}
