// src/features/comment/Comment.tsx
import { faPen, faShare } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useAppDispatch, useAppSelector } from 'app/hooks';
import { format, formatDistanceToNow } from 'date-fns';
import { selectUser } from 'features/user/userSlice';
import { UserComment } from 'models/userComment';
import { MutableRefObject, useRef, useState } from 'react';
import styles from './Comment.module.scss';
import { editComment } from './commentSlice';
import { DeleteButton } from './deleteButton/DeleteButton';
import { Score } from './score/Score';
import { Badge } from 'react-bootstrap';
import { AddComment } from './addComment/AddComment';

type CommentParams = {
    userComment:UserComment,
    repliedFrom?:number
}

export function Comment({userComment, repliedFrom}:CommentParams) {
    const dispatch = useAppDispatch()
    const commenter = userComment.user;
    const userImage = commenter.image.png
    const {currentUser} = useAppSelector(selectUser);

    const isOwnComment = commenter.username === currentUser.username;
    const commentSince = formatDistanceToNow(userComment.createdAt, {addSuffix: true}) 
    const commentDate = format(userComment.createdAt, 'MMMM d, yyyy hh:mm aa');
    const [editMode, setEditMode] = useState(false);
    const [replyMode, setReplyMode] = useState(false);
    const [displayedComment, setDisplayedComment] = useState(userComment.content);
    const isEditAllowed = isOwnComment && editMode;
    const contentClass = [styles.content];
    if(isEditAllowed) {
        contentClass.push(styles.editable);
    }
    const commentFieldRef = useRef(null);
    
    function toggleEdit (fieldRef:MutableRefObject<any>){
        if(!editMode) {
            setEditMode(true);
            fieldRef.current.focus();
        } else {
            setEditMode(false);
            setDisplayedComment(userComment.content);
        };
    }

    function toggleReply(){
        setReplyMode(!replyMode);
    }

    const saveEdit = ()=>{
        dispatch(editComment({content: displayedComment, id: userComment.id}))
            .then(()=>setEditMode(false));
    }    

    const actionButton = isOwnComment?
        <button className='borderless' onClick={()=>toggleEdit(commentFieldRef)}>
            <FontAwesomeIcon icon={faPen}/>
            Edit
        </button>
        : <button className='borderless' onClick={toggleReply}> <FontAwesomeIcon icon={faShare} flip='horizontal'/> Reply </button>

    const saveButton = isEditAllowed ? <button onClick={()=>saveEdit()}>
        UPDATE</button>:null;

    const deleteButton = isEditAllowed?
        <DeleteButton id={userComment.id} repliedFrom={repliedFrom}></DeleteButton>
        :null;

    const replies = userComment.replies.map((reply, index)=><Comment userComment={reply} repliedFrom={userComment.id} key={reply.id+'_'+index}></Comment>)
    const commentStyle = [styles.comments];
    if(replies.length > 0) {
        commentStyle.push(styles.withReplies);
    }
    
    return (
        <div className={styles.commentContainer}>
            <div className={commentStyle.join(' ')}>
                <Score commentId={userComment.id} score={userComment.score}  />
                <div className={styles.body}>
                    <div className={styles.commenthead}>
                        <img src={userImage} alt={"avatar of "+commenter.username}/>
                        <div>
                            <span>{commenter.username}</span>
                            {isOwnComment?<Badge className={styles.badge}>YOU</Badge>:null}
                            <span
                                className={styles.commentSince}
                                title={commentDate}>{commentSince}</span>
                        </div>
                        
                        <div className={styles.actionButtons}>
                            {deleteButton}
                            {actionButton}
                        </div>
                    </div>
                    
                    <div className={contentClass.join(' ')}>
                    
                        <textarea ref={commentFieldRef}
                            className={!isEditAllowed?'d-none':''}
                            value={displayedComment}
                            onChange={(e)=>setDisplayedComment(e.target.value)}>
                        </textarea>
                        { isEditAllowed?null :displayedComment }
                    </div>
                    <div className={styles.commentfoot}>
                        <div className={styles.actionButtons}>
                            {saveButton}
                        </div>
                    </div>

                </div>
                
            </div>
            {replies}

            {replyMode?<AddComment replyTo={{commentId:userComment.id, userName:commenter.username}} onSend={toggleReply}></AddComment>:null}
        </div>
    )
}

// angular/src/app/comment/comment.component.ts
import { Component, Input, ChangeDetectionStrategy, ChangeDetectorRef, OnInit } from '@angular/core';
import { UserComment } from './user-comment.model';
import { UserService } from '../user/user.service';
import { format, formatDistanceToNow } from 'date-fns';
import { FormControl } from '@angular/forms';
import { CommentService } from './comment.service';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommentComponent implements OnInit{
  @Input({required: true})
  comment:UserComment = UserComment.EMPTY;

  @Input()
  repliedFrom:number|null = null;

  commentStyle:string = 'comments';
  editMode = false;
  isEditAllowed = false;
  replyMode = false;

  editFieldControl = new FormControl('', {nonNullable: true});

  private _commentDate:string = '';
  get commentDate(){
    return this._commentDate;
  }

  private _commentSince:string = '';
  get commentSince(){
    return this._commentSince;
  }

  private _isOwnComment = false;
  get isOwnComment() {
    return this._isOwnComment
  };

  private _isFieldIsActive = false;
  get isFieldActive(){
    return this._isFieldIsActive;
  }

  get editFieldStyle (){
    return [
      !(this.isOwnComment && this.editMode)?'d-none':'',
      this.isFieldActive?'active':''
    ].join(' ');
  }

  constructor(
    private userService:UserService,
    private commentService:CommentService,
    private cd: ChangeDetectorRef
  ){}

  async ngOnInit(){

    if(this.comment.replies.length > 0) {
      this.commentStyle += ' withReplies';
    };
    
    this._commentDate = format(this.comment.createdAt, 'MMMM d, yyyy hh:mm aa');
    this._commentSince = formatDistanceToNow(this.comment.createdAt, {addSuffix: true});
    this.cd.markForCheck();
    


    this.userService.fetchCurrentUser()
      .then(user=>{
        this._isOwnComment = this.comment.user.username === user.username;
        this.cd.markForCheck();
      })
      .finally(()=>this.cd.detectChanges());
    

  }

  toggleEditMode(){
    this.editMode = !this.editMode;
    if(this.editMode) {
      this.editFieldControl.setValue(this.comment.content);
    }
  }

  setFieldIsActive(state:boolean){
    this._isFieldIsActive = state;
  }

  saveEdit(){
    this.commentService.editComment(this.comment.id, this.editFieldControl.value);
    this.editMode  = false;
  }

  toggleReply(){
    this.replyMode = !this.replyMode;
    this.cd.detectChanges();
    
  }

  closeReply(){
    this.replyMode = false;
    this.cd.markForCheck();
    
  }

}

<div class="{{commentStyle}}">
    <div>
        <app-score [score]=comment.score [commentId]=comment.id />
    </div>
    <div class="body">
        <div class="commenthead">
            <img src="{{comment.user.image.png}}" alt="image of {{comment.user.username}}" />
            <div>
                <span>{{comment.user.username}}</span>
                <span *ngIf=isOwnComment class='badge bg-primary'>YOU</span>
                <span class='commentSince' [title]=commentDate>{{commentSince}}</span>
            </div>
            <div class="actionButtons">
                <delete-button *ngIf="editMode" [commentId]="comment.id" [repliedFrom]="repliedFrom"></delete-button>                
                <button *ngIf="isOwnComment" class='borderless' (click)="toggleEditMode()">
                    <app-icon iconName="faPen"/>
                    Edit
                </button>
                <button *ngIf="!isOwnComment" class='borderless' (click)="toggleReply()">
                    <app-icon iconName="faShare" flip='horizontal'/>
                    Reply
                </button>
            </div>
        </div>
        
        <div class="content">
            <fieldset class="{{editFieldStyle}}" >
                <legend>Add a comment</legend>
                <textarea [formControl]="editFieldControl"
                    rows="3"
                    (focus)="setFieldIsActive(true)"
                    (blur)="setFieldIsActive(false)">
                </textarea>
            </fieldset>

            <ng-container *ngIf="!editMode">{{comment.content}}</ng-container>
        </div>
        <div class="commentfoot">
            <div class="actionButtons">
                <button (click)=saveEdit() *ngIf="editMode">
                    UPDATE</button>
            </div>
        </div>
    </div>   

</div>


<ng-container *ngFor="let reply of comment.replies">
    <app-comment [comment]=reply [repliedFrom]=comment.id />
</ng-container>

<app-addcomment *ngIf="replyMode" [replyTo]="comment.id" (onSend)="closeReply()"> </app-addcomment>
